"""empty message

Revision ID: cad718766bfe
Revises: f11585f68b96
Create Date: 2023-11-20 12:44:05.909700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad718766bfe'
down_revision = 'f11585f68b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_snippets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_snippets', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
