"""empty message

Revision ID: e1112e739382
Revises: cad718766bfe
Create Date: 2023-11-20 13:35:01.555595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1112e739382'
down_revision = 'cad718766bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_snippets', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_snippets', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
